# Generated by Django 4.1.4 on 2023-03-24 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perm",
            old_name="user",
            new_name="users",
        ),
    ]
